---
# Title: Role Samba4
#
# Author: bitfinity-nl
# File: tasks/ubt-2004-amd64/samba4-add-dc.yml.yml
#
# Description:
#   Add additional domain controller
#

- name: "Check OS if is allready DC"
  shell: "samba-tool domain info {{ ansible_default_ipv4.address }}"
  register: smb_dc_result
  ignore_errors: yes

- name: "Preseed Kerberos version 5: krb5-config/default_realm"
  raw: "echo krb5-config krb5-config/default_realm string {{ smb_realm }} | sudo debconf-set-selections"
  when:
    - smb_dc_result.failed == true

- name: "Preseed Kerberos version 5: krb5-config/add_servers_realm"
  raw: "echo krb5-config krb5-config/add_servers_realm string {{ smb_realm }} | sudo debconf-set-selections"
  when:
    - smb_dc_result.failed == true

- name: "Preseed PAM Configuration"
  raw: "echo libpam-runtime  libpam-runtime/profiles multiselect     unix, winbind, systemd, mkhomedir | sudo debconf-set-selections"
  when:
    - smb_dc_result.failed == true

#- name: "Update repositories (fix update_cache:yes not working)"
#  raw: apt update

- name: "Install APT packages"
  apt:
    pkg:
    - acl
    - samba
    - smbclient
    - krb5-config
    - krb5-user
    - winbind
    - libpam-winbind
    - libnss-winbind
    update_cache: yes

- name: "Disable systemd-resolved"
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: "Remove symlink /etc/resolv.conf"
  file:
    path: /etc/resolv.conf
    state: absent

- name: "Transfer new template /etc/resolv.conf"
  template:
    src: common/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644

- name: "Edit Fstab"
  replace:
    path: /etc/fstab
    regexp: 'errors=remount-ro 0'
    replace: 'user_xattr,acl,barrier=1,errors=remount-ro,relatime 0'
    backup: yes

- name: "Transfer adc/krb5.conf.j2 to /etc/krb5.conf"
  template:
    src: adc/krb5.conf.j2
    dest: /etc/krb5.conf

- name: "back-up the initial /etc/samba/smb.conf to /etc/samba/smb.conf.initial"
  copy:
    src: /etc/samba/smb.conf
    dest: /etc/samba/smb.conf.initial
    remote_src: yes
    force: no
  when:
    - smb_dc_result.failed == true

- name: "rm /etc/samba/smb.conf"
  file:
    path: /etc/samba/smb.conf
    state: absent
  when:
    - smb_dc_result.failed == true

- name: "Transfer adc/smb.conf.j2 to /etc/samba/smb.conf"
  template:
    src: adc/smb.conf.j2
    dest: /etc/samba/smb.conf

- name: "Join {{ ansible_hostname }} as additional domain controller"
  raw: "samba-tool domain join {{ smb_realm }} DC -U{{ smb_workgroup }}\\{{smb_username }} --dns-backend=SAMBA_INTERNAL --password={{ smb_password }}"
  when:
    - smb_dc_result.failed == true 

- name: "Configure DNS forwarder in /etc/samba/smb.conf"
  replace:
    path: /etc/samba/smb.conf
    regexp: '127.0.0.53' 
    replace: '{{ def_ad_dns_forwarder }}'
    backup: yes

- name: "Disable Services"
  systemd:
    enabled: no
    state: stopped
    name: "{{ item }}"
  with_items:
    - smbd
    - nmbd
    - winbind

- name: "Enable Services"
  systemd:
    masked: no
    enabled: yes
    state: started
    name: "{{ item }}"
  with_items:
    - samba-ad-dc.service

- name: "Reboot server when domain is provisioned"
  reboot:
  when:
    - smb_dc_result.failed == true

#- name: "Allow traffic for Application Samba4 AD-DC"
#  ufw:
#    rule: allow
#    name: Samba

#- name: "Allow all DNS traffic on port 53/tcp"
#  ufw:
#    rule: allow
#    port: '53'
#    proto: "{{ item }}"
#  with_items:
#    - tcp
#    - udp

- name: "Allow all Samba AD DC traffic"
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - { name: 'DNS (tcp)', port: '53', proto: 'tcp' }
    - { name: 'DNS (udp)', port: '53', proto: 'udp' }
    - { name: 'Kerberos (tcp)', port: '88', proto: 'tcp' }
    - { name: 'Kerberos (udp)', port: '88', proto: 'udp' }
    - { name: 'ntp', port: '123', proto: 'udp' }
    - { name: 'End Point Mapper (DCE/RPC Locator Service)', port: '135', proto: 'tcp' }
    - { name: 'NetBIOS Name Service', port: '137', proto: 'udp' }
    - { name: 'NetBIOS Datagram', port: '138', proto: 'udp' }
    - { name: 'NetBIOS Session', port: '139', proto: 'tcp' }
    - { name: 'LDAP (tcp)', port: '389', proto: 'tcp' }
    - { name: 'LDAP (udp)', port: '389', proto: 'udp' }
    - { name: 'SMB over TCP', port: '445', proto: 'tcp' }
    - { name: 'Kerberos kpasswd (tcp)', port: '464', proto: 'tcp' }
    - { name: 'Kerberos kpasswd (udp)', port: '464', proto: 'udp' }
    - { name: 'LDAPS', port: '636', proto: 'tcp' }
    - { name: 'Global Catalog', port: '3268', proto: 'tcp' }
    - { name: 'Global Catalog SSL', port: '3269', proto: 'tcp' }
    - { name: 'Dynamic RPC Ports', port: '49152:65535 ', proto: 'tcp' }

- name: "Ubuntu login"
  import_tasks: samba4-login.yml
