---
# Title: role-samba4
#
# Author: bitfinity-nl
# Version: 1.0
# File: tasks/main.yml
#
# Description: Creating a primairy Active Directory Domain Controller.
#

#- name: "Role: primary DC, For OS: Ubuntu 18.04LTS, Arch: amd64"
#  import_tasks: ubuntu-1804-amd64.yml
#  when:
#    - smb_role == "primary"
#    - ansible_distribution_version == "18.04"
#    - ansible_architecture == "x86_64"

- name: "Role: additional DC, For OS: Ubuntu 18.04LTS, Arch: amd64"
  import_tasks: ubt-2004-amd64/samba4-add-dc.yml
  when:
    - smb_role == "additional"
    - ansible_distribution_version == "20.04"
    - ansible_architecture == "x86_64"
    
- name: "Role: additional DC, For OS: Ubuntu 18.04LTS, Arch: amd64"
  import_tasks: ubt-1804-amd64/samba4-add-dc.yml
  when:
    - smb_role == "additional"
    - ansible_distribution_version == "18.04"
    - ansible_architecture == "x86_64"
